version: "3.0"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - </path/to/bazarr/config>:/config
      - </path/to/movies>:/movies
      - </path/to/tv>:/tv
    restart: ${RESTART_POLICY}
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /path/to/deluge/config:/config
      - /path/to/your/downloads:/downloads
    restart: ${RESTART_POLICY}
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - </path/to/appdata/config>:/config
    restart: ${RESTART_POLICY}
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - <path to data>:/config
      - <path to blackhole>:/downloads
    restart: ${RESTART_POLICY}
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - URL=${DOMAIN}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare 
      - EMAIL=${ADMIN_MAIL}
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 443:443
      - 80:80
    restart: ${RESTART_POLICY}
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - MYSQL_ROOT_PASSWORD=${ROOT_PW}
      - TZ=${TZ}
    volumes:
      - path_to_data:/config
    restart: ${RESTART_POLICY}
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    restart: ${RESTART_POLICY}
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /path/to/appdata/config:/config
    restart: ${RESTART_POLICY}
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: ${RESTART_POLICY}
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /path/to/data:/config
      - /path/to/movies:/movies
      - /path/to/downloadclient-downloads:/downloads
    restart: ${RESTART_POLICY}
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /path/to/data:/config
      - /path/to/tvseries:/tv
      - /path/to/downloadclient-downloads:/downloads
    restart: ${RESTART_POLICY}
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - <path to data>:/config
      - <path to plex logs>:/logs
    restart: ${RESTART_POLICY}
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - SERVERURL=wireguard.${DOMAIN}
      - SERVERPORT=51820
      - PEERS=${WIREGUARD_CLIENTS}
      - PEERDNS=${WIREGUARD_DNS}
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: ${RESTART_POLICY}
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
    restart: ${RESTART_POLICY}
  redis:
    image: redis:6.0-alpine
    container_name: redis
    restart: ${RESTART_POLICY}
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PI_PASSWORD}
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    restart: ${RESTART_POLICY}
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    environment:
      - API_KEY=${CLOUDFLARE_API}
      - ZONE=${DOMAIN}
      - SUBDOMAIN=${CLOUDFLARE_SUBDOMAIN}
      - PROXIED=${CLOUDFLARE_PROXIED}
    restart: ${RESTART_POLICY}
  netdata:
    image: netdata/netdata
    container_name: netdata
    environment:
      - PGID=${DOCKER_GID}
    hostname: netdata.${DOMAIN}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: ${RESTART_POLICY}
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path-to-data/:/data
    restart: ${RESTART_POLICY}
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: ${RESTART_POLICY}
  bitwarden:
    image: bitwardenrs/server-mysql
    container_name: bitwarden
    environment:
      - DOMAIN=https://bitwarden.${DOMAIN} 
      - ADMIN_TOKEN=ยง{BW_PASSWORD}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${BW_SMTP_HOST}
      - SMTP_FROM=${BW_SMTP_FROM}
      - SMTP_PORT=${BW_SMTP_PORT}
      - SMTP_SSL=true
      - SMTP_USERNAME=${BW_SMTP_USERNAME}
      - SMTP_PASSWORD=${BW_SMTP_PASSWORD}
      - SHOW_PASSWORD_HINT=false
      - ENABLE_DB_WAL=false
      - DATABASE_URL=${BW_DATABASE}
    volumes:
      - /bw-data/:/data/
    restart: ${RESTART_POLICY}
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - </path/to/appdata/config>:/config
      - </path/to/backups>:/backups
      - </path/to/source>:/source
    restart: ${RESTART_POLICY}
  gitea:
    image: gitea/gitea
    ports:
      - "3000:3000"
      - "22:22"
    volumes:
      - ./data:/data
    restart: ${RESTART_POLICY}